name: Main

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'altlinux'

permissions:
  contents: read
  pull-requests: read

jobs:
  lint-vala:
    name: Check vala files
    runs-on: alt-sisyphus
    container:
      image: altlinux.space/alt-gnome/coding-style-image:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check files
        uses: alt-gnome/coding-style-actions/vala@main

  test-build:
    name: Test Build
    runs-on: alt-sisyphus
    needs:
      - lint-vala
      - checkers

    steps:
      - name: Install libs on container
        run: |
          apt-get update
          apt-get install -y git meson vala "pkgconfig(json-glib-1.0)" "gir(Json)=1.0" "pkgconfig(gee-0.8)" "gir(Gee)=0.8" "pkgconfig(gio-2.0)" "pkgconfig(libsoup-3.0)" "gir(Soup)=3.0" "pkgconfig(json-glib-1.0)" "gobject-introspection-devel" valadoc /usr/bin/gtkdoc-scan
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        run: meson setup _build -Ddocumentation=true

      - name: Build
        run: meson compile -C _build

      - name: Deploy pages
        if: github.event_name != 'pull_request'
        uses: actions/deploy-pages@v1
        with:
          directory: ./_build/doc/libapi-base-5-vala

  build-altlinux:
    name: Build RPM for altlinux

    runs-on: alt-sisyphus
    container:
      image: altlinux.space/actions/runner/hasherc:sisyphus
    needs:
      - test-build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'altlinux'
          fetch-tags: true
          fetch-depth: 0

      - uses: alt-gnome/build-rpm-action@main
        name: Build RPMs

      - uses: alt-gnome/upload-rpm-action@main
        name: Upload RPMs
        if: github.event_name != 'pull_request'
        with:
          directory: ~/.cache/hasherc/libapi-base/out/RPMS
          token: ${{ secrets.TOKEN }}
          group: libapi-base
