#!/usr/bin/bash

version=$1

cp -a doc/serialize/serialize-$version doc/api-base/serialize-$version 

RPL="<li class=\"package\">serialize-$version</li>"
TRG="<li class=\"package\"><a href=\"serialize-$version/index.htm\">serialize-$version</a></li>"

FILE=doc/api-base/index.html
TMP_FILE=$(mktemp)

sed "s#$RPL#$TRG#g" "$FILE" > "$TMP_FILE"
mv "$TMP_FILE" "$FILE"
