#!/usr/bin/bash

version=$1

cp -a doc/serialize/libserialize-$version doc/api-base/libserialize-$version 

RPL="<li class=\"package\">libserialize-$version</li>"
TRG="<li class=\"package\"><a href=\"libserialize-$version/index.htm\">libserialize-$version</a></li>"

FILE=doc/api-base/index.html
TMP_FILE=$(mktemp)

sed "s#$RPL#$TRG#g" "$FILE" > "$TMP_FILE"
mv "$TMP_FILE" "$FILE"
